export const FakeData = [
  {
    id: 1,
    accountName: "Rajan Dubey",
    accountCode: "AC001",
    city: "Mumbai",
    address: "Andheri East",
    companyName: "TechNova Pvt Ltd",
    email: "rajan@technova.com",
    mobile: "9876543210",
    website: "www.technova.com",
    mfgCode: "MFG001",
    state: "Maharashtra",
    group: "Electronics",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 2,
    accountName: "Neha Sharma",
    accountCode: "AC002",
    city: "Delhi",
    address: "Connaught Place",
    companyName: "CodeMatrix Ltd",
    email: "neha@codematrix.com",
    mobile: "9988776655",
    website: "www.codematrix.com",
    mfgCode: "MFG002",
    state: "Delhi",
    group: "Software",
    country: "India",
    logo: null,
    type: "No",
  },
  {
    id: 3,
    accountName: "Amit Patel",
    accountCode: "AC003",
    city: "Ahmedabad",
    address: "Satellite",
    companyName: "GreenTech Systems",
    email: "amit@greentech.in",
    mobile: "9723456789",
    website: "www.greentech.in",
    mfgCode: "MFG003",
    state: "Gujarat",
    group: "Renewable Energy",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 4,
    accountName: "Priya Mehta",
    accountCode: "AC004",
    city: "Bangalore",
    address: "Whitefield",
    companyName: "SkyNet Solutions",
    email: "priya@skynet.com",
    mobile: "9123456789",
    website: "www.skynet.com",
    mfgCode: "MFG004",
    state: "Karnataka",
    group: "IT Services",
    country: "India",
    logo: null,
    type: "No",
  },
  {
    id: 5,
    accountName: "Rohit Verma",
    accountCode: "AC005",
    city: "Pune",
    address: "Kothrud",
    companyName: "NextGen Robotics",
    email: "rohit@nextgen.com",
    mobile: "9822113344",
    website: "www.nextgen.com",
    mfgCode: "MFG005",
    state: "Maharashtra",
    group: "Automation",
    country: "India",
    logo: null,
    type: "Yes",
  },
];

export const salesData = [
  { name: "Electronics", value: 400 },
  { name: "Fashion", value: 300 },
  { name: "Groceries", value: 300 },
  { name: "Furniture", value: 200 },
  { name: "Toys", value: 150 },
];

export const FakeCustomerData = [
  {
    id: 1,
    customerName: "Tata Steel Ltd.",
    contactPerson: "Rohit Sharma",
    email: "rohit.sharma@tatasteel.com",
    contactNo: "022-22334455",
    customerCode: "CUST001",
    designation: "Purchase Manager",
    mobileNo: "9876543210",
    fat: "5%",
    city: "Mumbai",
    pincode: "400020",
    tinNo: "TIN123456",
    panNo: "ABCDE1234F",
    cstNo: "CST654321",
    gstNo: "27ABCDE1234F1Z5",
    creditLimit: "₹10,00,000",
    creditDays: "30",
    sourceEmployee: "Amit Verma",
    exciseNo: "EXC12345",
    annualTurnover: "₹50 Cr",
    country: "India",
    state: "Maharashtra",
    customerType: "Corporate",
    activeStatus: true,
    gstExempt: false,
  },
  {
    id: 2,
    customerName: "Reliance Retail",
    contactPerson: "Anita Verma",
    email: "anita.verma@relianceretail.com",
    contactNo: "011-44556677",
    customerCode: "CUST002",
    designation: "Branch Manager",
    mobileNo: "9998877665",
    fat: "3%",
    city: "New Delhi",
    pincode: "110001",
    tinNo: "TIN654321",
    panNo: "PQRSX9876T",
    cstNo: "CST789654",
    gstNo: "07PQRSX9876T1Z2",
    creditLimit: "₹5,00,000",
    creditDays: "45",
    sourceEmployee: "Suman Joshi",
    exciseNo: "EXC56789",
    annualTurnover: "₹25 Cr",
    country: "India",
    state: "Delhi",
    customerType: "Wholesale",
    activeStatus: true,
    gstExempt: false,
  },
  {
    id: 3,
    customerName: "Big Bazaar",
    contactPerson: "Vikas Gupta",
    email: "vikas.gupta@bigbazaar.com",
    contactNo: "0522-4455667",
    customerCode: "CUST003",
    designation: "Sales Executive",
    mobileNo: "9988776655",
    fat: "2%",
    city: "Lucknow",
    pincode: "226001",
    tinNo: "TIN789456",
    panNo: "LMNOP4567Q",
    cstNo: "CST321654",
    gstNo: "09LMNOP4567Q1Z3",
    creditLimit: "₹2,00,000",
    creditDays: "15",
    sourceEmployee: "Ritu Singh",
    exciseNo: "EXC78912",
    annualTurnover: "₹8 Cr",
    country: "India",
    state: "Uttar Pradesh",
    customerType: "Retail",
    activeStatus: true,
    gstExempt: false,
  },
  {
    id: 4,
    customerName: "Walmart Inc.",
    contactPerson: "John Carter",
    email: "john.carter@walmart.com",
    contactNo: "+1 212-334-5566",
    customerCode: "CUST004",
    designation: "Procurement Lead",
    mobileNo: "+1 9876543210",
    fat: "7%",
    city: "New York",
    pincode: "10005",
    tinNo: "TINNY5432",
    panNo: "USPAN1234Y",
    cstNo: "CSTNY8765",
    gstNo: "USGST87654",
    creditLimit: "₹50,00,000",
    creditDays: "60",
    sourceEmployee: "Neha Rao",
    exciseNo: "EXC99876",
    annualTurnover: "₹100 Cr",
    country: "USA",
    state: "New York",
    customerType: "Corporate",
    activeStatus: true,
    gstExempt: true,
  },
  {
    id: 5,
    customerName: "Tesco PLC",
    contactPerson: "Emma Watson",
    email: "emma.watson@tesco.com",
    contactNo: "+44 20 7946 0958",
    customerCode: "CUST005",
    designation: "Finance Head",
    mobileNo: "+44 7894561230",
    fat: "6%",
    city: "London",
    pincode: "NW16XE",
    tinNo: "TIN12345",
    panNo: "ABCDE9999Z",
    cstNo: "CST56789",
    gstNo: "UKG9876543",
    creditLimit: "₹20,00,000",
    creditDays: "30",
    sourceEmployee: "Manish Mehta",
    exciseNo: "EXC11111",
    annualTurnover: "₹60 Cr",
    country: "UK",
    state: "Greater London",
    customerType: "Corporate",
    activeStatus: false,
    gstExempt: false,
  },
];

export const FakeBranchData = [
  {
    id: 1,
    branchName: "Mumbai HQ",
    contactPerson: "Rohit Sharma",
    email: "rohit.sharma@company.com",
    designation: "Branch Manager",
    mobileNo: "9876543210",
    address: "123 Marine Drive, Churchgate",
    fax: "022-22334455",
    contactNo: "022-99887766",
    pincode: "400020",
    cstNo: "CST12345",
    tinNo: "TIN56789",
    panNo: "ABCDE1234F",
    gstNo: "27ABCDE1234F1Z5",
    annualTurnover: "5 Cr",
    city: "Mumbai",
    country: "India",
    state: "Maharashtra",
  },
  {
    id: 2,
    branchName: "Delhi Branch",
    contactPerson: "Anita Verma",
    email: "anita.verma@company.com",
    designation: "Regional Head",
    mobileNo: "9998877665",
    address: "A-45 Connaught Place",
    fax: "011-33445566",
    contactNo: "011-99887744",
    pincode: "110001",
    cstNo: "CST54321",
    tinNo: "TIN98765",
    panNo: "PQRSX9876T",
    gstNo: "07PQRSX9876T1Z2",
    annualTurnover: "3 Cr",
    city: "New Delhi",
    country: "India",
    state: "Delhi",
  },
  {
    id: 3,
    branchName: "Lucknow Office",
    contactPerson: "Vikas Gupta",
    email: "vikas.gupta@company.com",
    designation: "Sales Executive",
    mobileNo: "9988776655",
    address: "45 Hazratganj Market",
    fax: "0522-2233445",
    contactNo: "0522-4455667",
    pincode: "226001",
    cstNo: "CST99887",
    tinNo: "TIN65432",
    panNo: "LMNOP4567Q",
    gstNo: "09LMNOP4567Q1Z3",
    annualTurnover: "1.2 Cr",
    city: "Lucknow",
    country: "India",
    state: "Uttar Pradesh",
  },
  {
    id: 4,
    branchName: "London Office",
    contactPerson: "John Carter",
    email: "john.carter@company.com",
    designation: "Operations Head",
    mobileNo: "+44 7894561230",
    address: "221B Baker Street",
    fax: "+44 20 7946 0958",
    contactNo: "+44 20 1234 5678",
    pincode: "NW16XE",
    cstNo: "CST56789",
    tinNo: "TIN12345",
    panNo: "ABCDE9999Z",
    gstNo: "UKG9876543",
    annualTurnover: "10 Cr",
    city: "London",
    country: "UK",
    state: "Greater London",
  },
];

export const FakeFollowUpActivityData = [
  {
    id: 1,
    dueDateTime: "2025-11-05T10:30",
    reminderDateTime: "2025-11-04T09:00",
    remarks: "Follow up with client about proposal status.",
    followUpStatusReason: "Client requested more time to decide.",
    assignFollowUp: "John Doe",
    followUpActivity: "Call Client",
    followUpActivityType: "Telephonic",
    priority: "High",
    followUpStatus: "Pending",
  },
  {
    id: 2,
    dueDateTime: "2025-11-08T15:00",
    reminderDateTime: "2025-11-07T12:00",
    remarks: "Send updated quotation and confirm meeting.",
    followUpStatusReason: "Quotation update required",
    assignFollowUp: "Priya Sharma",
    followUpActivity: "Send Email",
    followUpActivityType: "Email",
    priority: "Medium",
    followUpStatus: "In Progress",
  },
  {
    id: 3,
    dueDateTime: "2025-11-10T11:00",
    reminderDateTime: "2025-11-09T09:00",
    remarks: "Schedule follow-up demo for software feature.",
    followUpStatusReason: "Demo postponed by client",
    assignFollowUp: "Ravi Kumar",
    followUpActivity: "Product Demo",
    followUpActivityType: "Meeting",
    priority: "High",
    followUpStatus: "Scheduled",
  },
  {
    id: 4,
    dueDateTime: "2025-11-12T16:30",
    reminderDateTime: "2025-11-11T15:00",
    remarks: "Check in after delivery for feedback.",
    followUpStatusReason: "Awaiting delivery confirmation",
    assignFollowUp: "Anjali Singh",
    followUpActivity: "Feedback Call",
    followUpActivityType: "Phone",
    priority: "Low",
    followUpStatus: "Completed",
  },
];

export const FakeInterestedProductData = [
  {
    id: 1,
    productName: "Steel Rod 10mm",
    productCode: "SR-10",
    productShortDesc: "High tensile steel rod",
    productFullDesc:
      "10mm high-tensile steel rod suitable for construction and manufacturing applications.",
    size: "10mm",
    length: "6m",
    manufactureBrand: "Tata Steel",
    salePrice: "750",
    purchasePrice: "680",
    reorderQty: "100",
    minOrderQty: "50",
    cgst: "9",
    sgst: "9",
    igst: "18",
    productType: "Type A",
    productMainGroup: "Group 1",
    productSubGroup: "SubGroup 1",
    assemblyType: "Non-Assembled",
    saleUOM: "PCS",
    purchaseUOM: "PCS",
  },
  {
    id: 2,
    productName: "PVC Pipe 1 inch",
    productCode: "PVC-01",
    productShortDesc: "1 inch water pipe",
    productFullDesc:
      "Durable 1-inch PVC water pipe used for residential plumbing and irrigation.",
    size: "1 inch",
    length: "3m",
    manufactureBrand: "Supreme",
    salePrice: "120",
    purchasePrice: "100",
    reorderQty: "200",
    minOrderQty: "100",
    cgst: "9",
    sgst: "9",
    igst: "18",
    productType: "Type B",
    productMainGroup: "Group 2",
    productSubGroup: "SubGroup 2",
    assemblyType: "Non-Assembled",
    saleUOM: "PCS",
    purchaseUOM: "PCS",
  },
  {
    id: 3,
    productName: "Hydraulic Pump",
    productCode: "HP-250",
    productShortDesc: "Industrial hydraulic pump",
    productFullDesc:
      "Heavy-duty hydraulic pump used in industrial and automotive applications.",
    size: "Medium",
    length: "N/A",
    manufactureBrand: "Bosch",
    salePrice: "15000",
    purchasePrice: "14000",
    reorderQty: "10",
    minOrderQty: "2",
    cgst: "9",
    sgst: "9",
    igst: "18",
    productType: "Type C",
    productMainGroup: "Group 3",
    productSubGroup: "SubGroup 3",
    assemblyType: "Assembled",
    saleUOM: "PCS",
    purchaseUOM: "PCS",
  },
  {
    id: 4,
    productName: "Lubricant Oil 1L",
    productCode: "LO-1L",
    productShortDesc: "Engine lubricant oil",
    productFullDesc:
      "High-quality 1L engine lubricant oil suitable for cars, trucks, and machinery.",
    size: "1L",
    length: "N/A",
    manufactureBrand: "Castrol",
    salePrice: "480",
    purchasePrice: "420",
    reorderQty: "50",
    minOrderQty: "20",
    cgst: "9",
    sgst: "9",
    igst: "18",
    productType: "Type B",
    productMainGroup: "Group 2",
    productSubGroup: "SubGroup 1",
    assemblyType: "Non-Assembled",
    saleUOM: "LTR",
    purchaseUOM: "LTR",
  },
  {
    id: 5,
    productName: "Copper Wire Roll",
    productCode: "CW-50",
    productShortDesc: "50m copper wire roll",
    productFullDesc:
      "Pure copper electrical wire roll, 50 meters, used in household and industrial wiring.",
    size: "2mm",
    length: "50m",
    manufactureBrand: "Finolex",
    salePrice: "2500",
    purchasePrice: "2200",
    reorderQty: "25",
    minOrderQty: "10",
    cgst: "9",
    sgst: "9",
    igst: "18",
    productType: "Type A",
    productMainGroup: "Group 1",
    productSubGroup: "SubGroup 2",
    assemblyType: "Non-Assembled",
    saleUOM: "ROLL",
    purchaseUOM: "ROLL",
  },
];








