const FakeData = [
  {
    id: 1,
    accountName: "Rajan Dubey",
    accountCode: "AC001",
    city: "Mumbai",
    address: "Andheri East",
    companyName: "TechNova Pvt Ltd",
    email: "rajan@technova.com",
    mobile: "9876543210",
    website: "www.technova.com",
    mfgCode: "MFG001",
    state: "Maharashtra",
    group: "Electronics",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 2,
    accountName: "Neha Sharma",
    accountCode: "AC002",
    city: "Delhi",
    address: "Connaught Place",
    companyName: "CodeMatrix Ltd",
    email: "neha@codematrix.com",
    mobile: "9988776655",
    website: "www.codematrix.com",
    mfgCode: "MFG002",
    state: "Delhi",
    group: "Software",
    country: "India",
    logo: null,
    type: "No",
  },
  {
    id: 3,
    accountName: "Amit Patel",
    accountCode: "AC003",
    city: "Ahmedabad",
    address: "Satellite",
    companyName: "GreenTech Systems",
    email: "amit@greentech.in",
    mobile: "9723456789",
    website: "www.greentech.in",
    mfgCode: "MFG003",
    state: "Gujarat",
    group: "Renewable Energy",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 4,
    accountName: "Priya Mehta",
    accountCode: "AC004",
    city: "Bangalore",
    address: "Whitefield",
    companyName: "SkyNet Solutions",
    email: "priya@skynet.com",
    mobile: "9123456789",
    website: "www.skynet.com",
    mfgCode: "MFG004",
    state: "Karnataka",
    group: "IT Services",
    country: "India",
    logo: null,
    type: "No",
  },
  {
    id: 5,
    accountName: "Rohit Verma",
    accountCode: "AC005",
    city: "Pune",
    address: "Kothrud",
    companyName: "NextGen Robotics",
    email: "rohit@nextgen.com",
    mobile: "9822113344",
    website: "www.nextgen.com",
    mfgCode: "MFG005",
    state: "Maharashtra",
    group: "Automation",
    country: "India",
    logo: null,
    type: "Yes",
  },
];


export const salesData = [
  { name: "Electronics", value: 400 },
  { name: "Fashion", value: 300 },
  { name: "Groceries", value: 300 },
  { name: "Furniture", value: 200 },
  { name: "Toys", value: 150 },
];

export default FakeData;
