const FakeData = [ {
    id: 1,
    accountName: "Rajan Dubey",
    accountCode: "AC001",
    city: "Mumbai",
    address: "Andheri East",
    companyName: "TechNova Pvt Ltd",
    email: "rajan@technova.com",
    mobile: "9876543210",
    website: "www.technova.com",
    mfgCode: "MFG001",
    state: "Maharashtra",
    group: "Electronics",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 2,
    accountName: "Neha Sharma",
    accountCode: "AC002",
    city: "Delhi",
    address: "Connaught Place",
    companyName: "CodeMatrix Ltd",
    email: "neha@codematrix.com",
    mobile: "9988776655",
    website: "www.codematrix.com",
    mfgCode: "MFG002",
    state: "Delhi",
    group: "Software",
    country: "India",
    logo: null,
    type: "No",
  },
  {
    id: 3,
    accountName: "Amit Patel",
    accountCode: "AC003",
    city: "Ahmedabad",
    address: "Satellite",
    companyName: "GreenTech Systems",
    email: "amit@greentech.in",
    mobile: "9723456789",
    website: "www.greentech.in",
    mfgCode: "MFG003",
    state: "Gujarat",
    group: "Renewable Energy",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 4,
    accountName: "Priya Mehta",
    accountCode: "AC004",
    city: "Bangalore",
    address: "Whitefield",
    companyName: "SkyNet Solutions",
    email: "priya@skynet.com",
    mobile: "9123456789",
    website: "www.skynet.com",
    mfgCode: "MFG004",
    state: "Karnataka",
    group: "IT Services",
    country: "India",
    logo: null,
    type: "No",
  },
//   {
//     id: 5,
//     accountName: "Karan Singh",
//     accountCode: "AC005",
//     city: "Chandigarh",
//     address: "Sector 17",
//     companyName: "AeroTech Pvt Ltd",
//     email: "karan@aerotech.in",
//     mobile: "9811122233",
//     website: "www.aerotech.in",
//     mfgCode: "MFG005",
//     state: "Punjab",
//     group: "Aerospace",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 6,
//     accountName: "Simran Kaur",
//     accountCode: "AC006",
//     city: "Amritsar",
//     address: "Mall Road",
//     companyName: "BrightWorks Ltd",
//     email: "simran@brightworks.com",
//     mobile: "9813344556",
//     website: "www.brightworks.com",
//     mfgCode: "MFG006",
//     state: "Punjab",
//     group: "Lighting",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
//   {
//     id: 7,
//     accountName: "Rohit Verma",
//     accountCode: "AC007",
//     city: "Pune",
//     address: "Kothrud",
//     companyName: "NextGen Robotics",
//     email: "rohit@nextgen.com",
//     mobile: "9822113344",
//     website: "www.nextgen.com",
//     mfgCode: "MFG007",
//     state: "Maharashtra",
//     group: "Automation",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 8,
//     accountName: "Sneha Iyer",
//     accountCode: "AC008",
//     city: "Chennai",
//     address: "T Nagar",
//     companyName: "BlueOcean Tech",
//     email: "sneha@blueocean.in",
//     mobile: "9840098765",
//     website: "www.blueocean.in",
//     mfgCode: "MFG008",
//     state: "Tamil Nadu",
//     group: "Marine",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
//   {
//     id: 9,
//     accountName: "Manish Gupta",
//     accountCode: "AC009",
//     city: "Lucknow",
//     address: "Hazratganj",
//     companyName: "AlphaChem Industries",
//     email: "manish@alphachem.in",
//     mobile: "9810020030",
//     website: "www.alphachem.in",
//     mfgCode: "MFG009",
//     state: "Uttar Pradesh",
//     group: "Chemicals",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 10,
//     accountName: "Anjali Desai",
//     accountCode: "AC010",
//     city: "Surat",
//     address: "Ring Road",
//     companyName: "FashionVista Pvt Ltd",
//     email: "anjali@fashionvista.in",
//     mobile: "9898123456",
//     website: "www.fashionvista.in",
//     mfgCode: "MFG010",
//     state: "Gujarat",
//     group: "Textile",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
//   {
//     id: 11,
//     accountName: "Vikram Joshi",
//     accountCode: "AC011",
//     city: "Indore",
//     address: "MG Road",
//     companyName: "NutriLife Foods",
//     email: "vikram@nutrilife.in",
//     mobile: "9823456789",
//     website: "www.nutrilife.in",
//     mfgCode: "MFG011",
//     state: "Madhya Pradesh",
//     group: "Food & Beverages",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 12,
//     accountName: "Pooja Nair",
//     accountCode: "AC012",
//     city: "Kochi",
//     address: "Marine Drive",
//     companyName: "EcoWave Pvt Ltd",
//     email: "pooja@ecowave.com",
//     mobile: "9847654321",
//     website: "www.ecowave.com",
//     mfgCode: "MFG012",
//     state: "Kerala",
//     group: "Environment",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
//   {
//     id: 13,
//     accountName: "Arjun Kapoor",
//     accountCode: "AC013",
//     city: "Jaipur",
//     address: "MI Road",
//     companyName: "SolarEdge Systems",
//     email: "arjun@solaredge.in",
//     mobile: "9828345678",
//     website: "www.solaredge.in",
//     mfgCode: "MFG013",
//     state: "Rajasthan",
//     group: "Solar Energy",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 14,
//     accountName: "Meera Bansal",
//     accountCode: "AC014",
//     city: "Nagpur",
//     address: "Dharampeth",
//     companyName: "AutoZone Components",
//     email: "meera@autozone.com",
//     mobile: "9829090909",
//     website: "www.autozone.com",
//     mfgCode: "MFG014",
//     state: "Maharashtra",
//     group: "Automotive",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
//   {
//     id: 15,
//     accountName: "Deepak Chawla",
//     accountCode: "AC015",
//     city: "Bhopal",
//     address: "Arera Colony",
//     companyName: "SmartLink Technologies",
//     email: "deepak@smartlink.in",
//     mobile: "9822122233",
//     website: "www.smartlink.in",
//     mfgCode: "MFG015",
//     state: "Madhya Pradesh",
//     group: "Networking",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 16,
//     accountName: "Shreya Ghosh",
//     accountCode: "AC016",
//     city: "Kolkata",
//     address: "Salt Lake",
//     companyName: "UrbanTech Solutions",
//     email: "shreya@urbantech.in",
//     mobile: "9877765432",
//     website: "www.urbantech.in",
//     mfgCode: "MFG016",
//     state: "West Bengal",
//     group: "IT Infrastructure",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
//   {
//     id: 17,
//     accountName: "Rahul Sinha",
//     accountCode: "AC017",
//     city: "Patna",
//     address: "Fraser Road",
//     companyName: "AgroPlus Ltd",
//     email: "rahul@agroplus.in",
//     mobile: "9834456677",
//     website: "www.agroplus.in",
//     mfgCode: "MFG017",
//     state: "Bihar",
//     group: "Agriculture",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 18,
//     accountName: "Divya Jain",
//     accountCode: "AC018",
//     city: "Noida",
//     address: "Sector 62",
//     companyName: "HealthSync Pvt Ltd",
//     email: "divya@healthsync.in",
//     mobile: "9811122334",
//     website: "www.healthsync.in",
//     mfgCode: "MFG018",
//     state: "Uttar Pradesh",
//     group: "Healthcare",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
//   {
//     id: 19,
//     accountName: "Nikhil Rao",
//     accountCode: "AC019",
//     city: "Hyderabad",
//     address: "Hitech City",
//     companyName: "CyberLink Systems",
//     email: "nikhil@cyberlink.in",
//     mobile: "9900990099",
//     website: "www.cyberlink.in",
//     mfgCode: "MFG019",
//     state: "Telangana",
//     group: "Technology",
//     country: "India",
//     logo: null,
//     type: "Yes",
//   },
//   {
//     id: 20,
//     accountName: "Ayesha Khan",
//     accountCode: "AC020",
//     city: "Bhopal",
//     address: "TT Nagar",
//     companyName: "AquaPure Pvt Ltd",
//     email: "ayesha@aquapure.in",
//     mobile: "9911223344",
//     website: "www.aquapure.in",
//     mfgCode: "MFG020",
//     state: "Madhya Pradesh",
//     group: "Water Treatment",
//     country: "India",
//     logo: null,
//     type: "No",
//   },
]

export default FakeData